//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_content_Questions
    {
        public int question_id { get; set; }
        public string question { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public Nullable<int> correct_option_number { get; set; }
        public int content_id { get; set; }
        public string content_name { get; set; }
        public int topic_id { get; set; }
        public string topic_name { get; set; }
        public int level_id { get; set; }
        public string question_level { get; set; }
    }
}
