//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_exam_questions
    {
        public int exam_question_id { get; set; }
        public int exam_id { get; set; }
        public int question_id { get; set; }
        public Nullable<int> student_submitted_option { get; set; }
        public string question { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
    }
}
