//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Level_Questions
    {
        public int level_id { get; set; }
        public string question_level { get; set; }
        public int question_id { get; set; }
        public string question { get; set; }
        public Nullable<int> correct_option_number { get; set; }
    }
}
