//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortalApplicationUsingApis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CIIT_CRMDBEntities : DbContext
    {
        public CIIT_CRMDBEntities()
            : base("name=CIIT_CRMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbladmin_details> tbladmin_details { get; set; }
        public DbSet<tblcontent_questions> tblcontent_questions { get; set; }
        public DbSet<tblemployee_details> tblemployee_details { get; set; }
        public DbSet<tblinterview_questions> tblinterview_questions { get; set; }
        public DbSet<tbllevel> tbllevels { get; set; }
        public DbSet<tblrole> tblroles { get; set; }
        public DbSet<tblstudent_details> tblstudent_details { get; set; }
        public DbSet<tblstudent_exam_details> tblstudent_exam_details { get; set; }
        public DbSet<tblstudent_exam_questions> tblstudent_exam_questions { get; set; }
        public DbSet<tbltopic> tbltopics { get; set; }
        public DbSet<tbltopic_contents> tbltopic_contents { get; set; }
        public DbSet<vw_content_Questions> vw_content_Questions { get; set; }
        public DbSet<vw_exam_details> vw_exam_details { get; set; }
        public DbSet<vw_exam_questions> vw_exam_questions { get; set; }
        public DbSet<vw_Level_Questions> vw_Level_Questions { get; set; }
        public DbSet<vw_student_details> vw_student_details { get; set; }
        public DbSet<vw_topic_contents> vw_topic_contents { get; set; }
    }
}
