//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortalApplicationUsingApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcontent_questions
    {
        public tblcontent_questions()
        {
            this.tblstudent_exam_questions = new HashSet<tblstudent_exam_questions>();
        }
    
        public int question_id { get; set; }
        public Nullable<int> content_id { get; set; }
        public string question { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public Nullable<int> correct_option_number { get; set; }
        public Nullable<int> level_id { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual tbltopic_contents tbltopic_contents { get; set; }
        public virtual ICollection<tblstudent_exam_questions> tblstudent_exam_questions { get; set; }
        public virtual tbllevel tbllevel { get; set; }
    }
}
