//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortalApplicationUsingApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllevel
    {
        public tbllevel()
        {
            this.tblcontent_questions = new HashSet<tblcontent_questions>();
        }
    
        public int level_id { get; set; }
        public string question_level { get; set; }
    
        public virtual ICollection<tblcontent_questions> tblcontent_questions { get; set; }
    }
}
