//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortalApplicationUsingApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblrole
    {
        public tblrole()
        {
            this.tblemployee_details = new HashSet<tblemployee_details>();
        }
    
        public int role_id { get; set; }
        public string role_name { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual ICollection<tblemployee_details> tblemployee_details { get; set; }
    }
}
