//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortalApplicationUsingApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstudent_exam_details
    {
        public tblstudent_exam_details()
        {
            this.tblstudent_exam_questions = new HashSet<tblstudent_exam_questions>();
        }
    
        public int exam_id { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<int> student_id { get; set; }
        public string status { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual tblstudent_details tblstudent_details { get; set; }
        public virtual ICollection<tblstudent_exam_questions> tblstudent_exam_questions { get; set; }
    }
}
