//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortalApplicationUsingApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstudent_exam_questions
    {
        public int exam_question_id { get; set; }
        public Nullable<int> exam_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> student_submitted_option { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual tblcontent_questions tblcontent_questions { get; set; }
        public virtual tblstudent_exam_details tblstudent_exam_details { get; set; }
    }
}
