//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortalApplicationUsingApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltopic
    {
        public tbltopic()
        {
            this.tbltopic_contents = new HashSet<tbltopic_contents>();
        }
    
        public int topic_id { get; set; }
        public string topic_name { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual ICollection<tbltopic_contents> tbltopic_contents { get; set; }
    }
}
