//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortalApplicationUsingApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltopic_contents
    {
        public tbltopic_contents()
        {
            this.tblcontent_questions = new HashSet<tblcontent_questions>();
            this.tblinterview_questions = new HashSet<tblinterview_questions>();
        }
    
        public int content_id { get; set; }
        public string content_name { get; set; }
        public Nullable<int> topic_id { get; set; }
        public string video_url { get; set; }
        public string ppts { get; set; }
        public string description { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual ICollection<tblcontent_questions> tblcontent_questions { get; set; }
        public virtual ICollection<tblinterview_questions> tblinterview_questions { get; set; }
        public virtual tbltopic tbltopic { get; set; }
    }
}
