//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortalApplicationUsingApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_exam_details
    {
        public int student_id { get; set; }
        public string student_code { get; set; }
        public string student_name { get; set; }
        public int exam_id { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public int exam_question_id { get; set; }
        public Nullable<int> student_submitted_option { get; set; }
    }
}
