//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortalApplicationUsingApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_topic_contents
    {
        public int content_id { get; set; }
        public string content_name { get; set; }
        public string video_url { get; set; }
        public int topic_id { get; set; }
        public string topic_name { get; set; }
    }
}
